//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Cursos_WPF.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class RelUserCourse
    {
        public int RelUserCourseId { get; set; }
        public int UserId { get; set; }
        public int CourseId { get; set; }
    }
}
